### PR TITLE
Chapter1.md 작성

### PR DESCRIPTION
**Pull request by jihyeon117**

### CODE REVIEW

**Comment by silversheep26** [comment]
very very good

**Comment by jihyeon117** [comment]
인사신사숙녀여러분GIF

**Review by been1118 — APPROVED** [review]
DanceHappyGIF

**Review by silversheep26 — CHANGES_REQUESTED** [review]
good

**Review by silversheep26 — APPROVED** [review]
흐헝

**Comment by jihyeon117** [comment]
감사합니다고마워땡큐고마워요마이클스캇마이클스캇오피스스티브GIF

**Review by silversheep26 — APPROVED** [review]
image

**Comment by jihyeon117** [comment]
앗 죄성.....

**Review by silversheep26 — APPROVED** [review]
image

**Pull request merged**
